version: "3.9"

services:
  backend:
    container_name: pos_solution_backend
    build: ./pos_solution_backend
    ports:
      - "8080:8080"
    volumes:
      - ./pos_solution_data:/data
    restart: always

  frontend:
    container_name: pos_solution_frontend
    build: ./pos_solution_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
